export default {
  id: "unikey",
  alias: "unikey",
  uiAlias: "unikey",
  display: {
    name: "UniKey",
    icon: "key",
    color: "#6C5CE7",
    textIcon: "UK",
    website: "https://www.getunikey.ai",
    notice: {
      apiKeyUrl: "https://www.getunikey.ai/console/token",
      text: "Bills in credits (1 credit = $0.01). Remaining is computed as a 5000-credit grant minus spend; set providerSpecificData.unikeyTotalCredits to your real grant if it differs, or unikeyProbeBalance: true to read the exact balance from the relay.",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://www.getunikey.ai/v1/chat/completions",
    modelsUrl: "https://www.getunikey.ai/v1/models",
    validateUrl: "https://www.getunikey.ai/v1/models",
    thinkingFormat: "openai",
  },
  // Chat-capable subset of the relay's catalog. /v1/models also advertises image,
  // video and embedding ids (kling, seedance, seedream, gpt-image, bge-m3) which
  // reject POST /v1/chat/completions with 400 "is a video generation model" /
  // "does not support this endpoint" — listing them here would only produce
  // requests that cannot succeed. passthroughModels keeps the full live catalog
  // reachable, so nothing upstream is lost; this list is what chat can use.
  models: [
    { id: "gpt-6-astra", name: "GPT-6 Astra" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
    { id: "google/gemini-3-pro-image", name: "Gemini 3 Pro Image" },
    { id: "x-ai/grok-4.3", name: "Grok 4.3" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "z-ai/glm-5.2", name: "GLM 5.2" },
    { id: "z-ai/glm-5.1", name: "GLM 5.1" },
    { id: "minimax/minimax-m3", name: "MiniMax M3" },
    { id: "moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMax-M3", name: "MiniMax M3 (Direct)" },
    { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4-8", name: "Claude Opus 4.8" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash (Direct)" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro (Direct)" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash (Direct)" },
    { id: "glm-5.1", name: "GLM 5.1 (Direct)" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code (Direct)" },
    { id: "kimi-k3", name: "Kimi K3 (Direct)" },
    { id: "qwen3.7-max", name: "Qwen3.7 Max" },
  ],
  modelsFetcher: { url: "https://www.getunikey.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: {
    usage: true,
    usageApikey: true,
  },
};
